$env:PATH = @(
   'C:\Program Files\Android\Android Studio\jbr\bin'
   'C:\Users\Steven\AppData\Local\Android\Sdk\build-tools\31.0.0'
   'C:\Users\Steven\AppData\Local\Android\Sdk\emulator'
   'C:\Users\Steven\AppData\Local\Android\Sdk\platform-tools'
   'C:\Users\Steven\go\bin'
   'C:\python\Scripts'
   'D:\go\bin'
   'D:\jadx\bin'
) -Join ';'
